// THIS IS A TEST, TO MAKE SURE ECLIPSE/GIT INTEGRATION IS SUCCESSFUL.

################################################################################

Stuff going to be added soon, but for now, this version will not have a config, 
only a set of predetermined ranks. Coming next version.

################################################################################